name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  AZURE_FUNCTIONAPP_NAME: function-ghstattracker
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/GitHubStatTracker.Function/'
  AZURE_WEBAPP_NAME: ghst
  AZURE_WEBAPP_PACKAGE_PATH: 'src/GitHubStatTracker.Web/'
  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        

    - name: 'Build Function'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Build WebApp'
      shell: bash
      run: |
        pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output'
        
    
